### ISSUE TITLE
Where does Pathway identifier come from?

### ISSUE THREAD

**Issue by heartonbit** [dhimmel/pathways#2]
While I validate Hetionet by comparing with original data sources, I stuck with Pathway.
What is the meaning of "Reactome via Pathway Commons"?
Pathway nodes in Hetionet have “PC7_digits” patterned ids.  
However, I cannot find such id neither from Pathway Commons nor Reactome which have “R-HSA-digis” style ids.
I wonder if Pathway Commons is used as it is not in the list and how I can find the original data.

**Comment by heartonbit** [comment]
I found the answer from [the code](https://github.com/dhimmel/pathways/blob/master/merge-resources.ipynb)

PC7 means Pathway Commons version 7 and digits after the underscore is just sequence number. 
So, the id is not something I look for. 

from https://github.com/dhimmel/pathways/blob/master/merge-resources.ipynb
```python
for name, description, genes in read_gmt(path):
... 
    # Add pathway
    i += 1    
    row = PC_Row(
        identifier = 'PC7_{}'.format(i),
        name = name,
        source = description['datasource'],
        genes = genes,
    )
    rows.append(row)
```

I try to parse the original gmt file to get the same sequence numbers.

**Comment by dhimmel** [comment]
@heartonbit thanks for the issue and digging through the source code! Cheers.

> PC7 means Pathway Commons version 7 and digits after the underscore is just sequence number. So, the id is not something I look for.

Right, `identifier` appears to be just an internal ID here.
